include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_final_locals: true
    prefer_function_declarations_over_variables: false
    use_super_parameters: true
    depend_on_referenced_packages: true
    use_build_context_synchronously: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    one_member_abstracts: true
    only_throw_errors: true
    package_api_docs: true
    prefer_final_in_for_each: true
    always_use_package_imports: true
    prefer_const_constructors: true
