name: flutter_accessorysetup
description: "A Flutter plugin to use AccessorySetupKit from iOS 18+"
version: 0.0.2
homepage: https://github.com/dotintent/flutter-accessorysetup

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.3
  objective_c: ^4.0.0

dev_dependencies:
  ffigen: ^16.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
