name: flutter_accessorysetup
description: >-
  Use it to discover and configure Bluetooth or Wi-Fi accessories with images and names provided by the app.
  Works on iOS 18 and above, and uses AccessorySetupKit through FFI.
version: 1.0.0
homepage: https://github.com/dotintent/flutter-accessorysetup

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.3
  objective_c: ^4.0.0

dev_dependencies:
  ffigen: ^16.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
